spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ua_logistics
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  mvc:
    media-types:
      type:
        json:
          - application/json

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days