export enum Role {
    BRIGADE_COMMANDER = 'BRIGADE_COMMANDER',
    BATTALION_COMMANDER = 'BATTALION_COMMANDER',
    COMPANY_COMMANDER = 'COMPANY_COMMANDER',
    PLAT_COMMANDER = 'PLAT_COMMANDER',
    LOGISTIC_COMMANDER = 'LOGISTIC_COMMANDER',
    SCANNING_DEVICE = 'SCANNING_DEVICE',
    ADMIN = 'ADMIN'
  }